import { Jost } from "next/font/google";
import Header from "@/components/global/Header";
import "./globals.css";

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-jost",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Header />
        <div className="root pt-28">
          {children}
        </div>
      </body>
    </html>
  );
}
